version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.10"             # must be a string!
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
